salesforce/assignment/force-app/main/default/objects/Case/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce/assignment/force-app/main/default/objects/Case/fields/Survey_send_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Survey_send_to_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey send to Customer</label>
    <type>Checkbox</type>
</CustomField>

salesforce/assignment/force-app/main/default/classes/test_batch.cls
@isTest
public class test_batch {
   
    static testmethod void test() {
		List<Case> clist = new List<Case>();
		case c = new Case(Status='Cancelled',SuppliedEmail='bhargav.baldev@aimdek.com',Language__c='english',Survey_send_to_Customer__c=true);
		clist.add(c);
		insert clist;        
        test.startTest();
        sendEmail b = New sendEmail();
        Database.executeBatch(b);
        test.stoptest();
    }
    
}