salesforce/assignment/force-app/main/default/objects/Case/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce/assignment/force-app/main/default/objects/survey_fquestion__c/survey_fquestion__c.object-meta.xml
<CustomObject>
    <label>survey fquestion</label>
    <nameField>
        <label>survey fquestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>survey fquestions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment/force-app/main/default/objects/survey_question__c/survey_question__c.object-meta.xml
<CustomObject>
    <label>survey question</label>
    <nameField>
        <label>Survey question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>survey questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment/force-app/main/default/objects/survey_response__c/survey_response__c.object-meta.xml
<CustomObject>
    <label>survey response</label>
    <nameField>
        <label>survey response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>survey responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/assignment/force-app/main/default/objects/survey_response__c/fields/survey_question__c.field-meta.xml
<CustomField>
    <fullName>survey_question__c</fullName>
    <label>survey question</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce/assignment/force-app/main/default/classes/surveyLWC.cls
public with sharing class surveyLWC {
 
    
 	@AuraEnabled(cacheable=true)
    public static List<sObject> getQuestion(String id){
     System.debug(id);
        Case que_type=[select Language__c from Case where id=:id];
        if(que_type.Language__c=='fr'){
          
            return Database.query('select id,name from survey_fquestion__c');
            
        } else {
    		return Database.query('select id,name from survey_question__c');    
        }
        
    }
    @AuraEnabled
    public static List<String> getStatus(String id){
       
        List<String> ca = new List<String>();
        List<Case> c = [select Status,Language__c from Case where id=:id];
        String status = c[0].Status;
        string lang = c[0].Language__c;
        ca.add(status);
        ca.add(lang);
        
        return ca;
    }
    @AuraEnabled
    public static void saveResponse(survey_response__c con,String id){
       
        System.debug(id);
        Case st = [select Status from Case where id=:id];
          System.debug(con); 
        try{
            
            if(st.Status=='Cancelled'){
            insert con;
            } 
        }catch(Exception e){
            System.debug('--->'+e);
        }
    }
    @AuraEnabled
    public static void setStatus(String status,String id){
        Case st = [select Status from Case where id=:id];
        st.Status=status;
        update st;
    }
    
    
}